# Generated by Django 5.2.5 on 2025-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('description', models.TextField(default='No description')),
                ('thumbnail_url', models.FileField(upload_to='thumbnails')),
                ('video_file', models.FileField(upload_to='video')),
                ('category', models.CharField(choices=[('ent', 'Entertainment'), ('edu', 'Education'), ('nat', 'Nature'), ('oth', 'Other')], default='oth', max_length=20)),
            ],
        ),
    ]
