# Generated by Django 5.2.5 on 2025-08-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('video_file', models.FileField(upload_to='videos')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
