# Generated by Django 5.2.5 on 2025-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
