# Generated by Django 5.2.5 on 2025-09-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('education', 'Education'), ('nature', 'Nature'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
