# Generated by Django 5.2.5 on 2025-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
